import {
    Palette,
    BookOpen,
    Library,
    Download,
    Image,
    Target,
    Database,
    Search,
    History,
    Smartphone,
    AppWindow,
    Server,
    LucideIcon,
} from "lucide-react";

export const CATEGORIES = [
    "Appearance",
    "Reader",
    "Library",
    "Downloads",
    "Images",
    "Tracking",
    "Backup",
    "Browse",
    "History",
    "Device",
    "Client",
    "Server",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const CATEGORY_ICONS: Record<Category, LucideIcon> = {
    Appearance: Palette,
    Reader: BookOpen,
    Library: Library,
    Downloads: Download,
    Images: Image,
    Tracking: Target,
    Backup: Database,
    Browse: Search,
    History: History,
    Device: Smartphone,
    Client: AppWindow,
    Server: Server,
};

export const CATEGORY_MAPPING: Record<Category, string[]> = {
    Appearance: [
        "webUIFlavor",
        "initialOpenInBrowserEnabled",
        "webUIInterface",
        "webUIChannel",
        "webUIUpdateCheckInterval",
        "systemTrayEnabled",
    ],
    Reader: [],
    Library: [
        "excludeEntryWithUnreadChapters",
        "excludeUnreadChapters",
        "excludeNotStarted",
        "excludeCompleted",
        "globalUpdateInterval",
        "updateMangas",
    ],
    Downloads: [
        "downloadAsCbz",
        "downloadsPath",
        "autoDownloadNewChapters",
        "autoDownloadNewChaptersLimit",
        "autoDownloadIgnoreReUploads",
    ],
    Images: ["downloadConversions", "serveConversions"],
    Tracking: [],
    Backup: [
        "backupPath",
        "backupTime",
        "backupInterval",
        "backupTTL",
        "autoBackupIncludeCategories",
        "autoBackupIncludeChapters",
        "autoBackupIncludeClientData",
        "autoBackupIncludeHistory",
        "autoBackupIncludeManga",
        "autoBackupIncludeServerSettings",
        "autoBackupIncludeTracking",
    ],
    Browse: [
        "extensionRepos",
        "maxSourcesInParallel",
        "localSourcePath",
        "opdsUseBinaryFileSizes",
        "opdsItemsPerPage",
        "opdsEnablePageReadProgress",
        "opdsMarkAsReadOnDownload",
        "opdsShowOnlyUnreadChapters",
        "opdsShowOnlyDownloadedChapters",
        "opdsChapterSortOrder",
        "opdsCbzMimetype",
    ],
    History: [],
    Device: [
        "koreaderSyncChecksumMethod",
        "koreaderSyncStrategyBackward",
        "koreaderSyncStrategyForward",
        "koreaderSyncPercentageTolerance",
    ],
    Client: ["electronPath"],
    Server: [
        "ip",
        "port",
        "socksProxyEnabled",
        "socksProxyVersion",
        "socksProxyHost",
        "socksProxyPort",
        "socksProxyUsername",
        "socksProxyPassword",
        "authMode",
        "authPassword",
        "authUsername",
        "jwtAudience",
        "jwtTokenExpiry",
        "jwtRefreshExpiry",
        "debugLogsEnabled",
        "maxLogFileSize",
        "maxLogFiles",
        "maxLogFolderSize",
        "flareSolverrEnabled",
        "flareSolverrUrl",
        "flareSolverrTimeout",
        "flareSolverrSessionName",
        "flareSolverrSessionTtl",
        "flareSolverrAsResponseFallback",
        "databaseType",
        "databaseUrl",
        "databaseUsername",
        "databasePassword",
        "useHikariConnectionPool",
    ],
};
